version: "3.7"

services:
  mongodb:
    container_name: configs
    image: mongo:4.0.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_NAME
    ports:
      - "57017:27017"
    volumes:
      - ./volumes/db:/data/db
    restart: "on-failure"

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54.0
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWORD
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=$DB_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD=$DB_PASSWORD
    ports:
      - '8081:8081'
    volumes:
      - ./volumes/db:/data/db
    restart: "on-failure"