version: "3.7"

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.0.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_NAME
    ports:
      - "57017:27017"
    volumes:
      - ./volumes/db:/data/db
    restart: "on-failure"

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54.0
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWORD
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=$DB_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD=$DB_PASSWORD
    ports:
      - '8081:8081'
    volumes:
      - ./volumes/db:/data/db
    restart: "on-failure"

# Uncomment the section below and change example-api by your docker image tag
# You need to build your docker image first to make it working and test if everything work for deployment

#  api-rest:
#    container_name: api-rest
#    image: example-api
#    depends_on:
#      - mongodb
#    environment:
#      - DB_NAME=$DB_NAME
#      - DB_USERNAME=$DB_USERNAME
#      - DB_PASSWORD=$DB_PASSWORD
#      - API_PORT=8080
#      - DB_PORT=27017
#      - ENVIRONMENT=$ENVIRONMENT
#      - MONGO_HOST=mongodb
#    ports:
#      - '8080:8080'
#    restart: "on-failure"
